package it.gc.covid19.fe;

import java.util.ArrayList;
import java.util.List;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.web.client.RestTemplate;

import it.gc.covid19.fe.bean.ComboB;

@SpringBootApplication
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

	@Bean
	public RestTemplate restTemplate(RestTemplateBuilder builder) {
		return builder.build();
	}

	@Bean(name = "elencoRegioni")
	public List<ComboB> elencoRegioni() {
		List<ComboB> er = new ArrayList<ComboB>();
		ComboB abruzzo = new ComboB("13", "Abruzzo");
		ComboB basilicata = new ComboB("17", "Basilicata");
		ComboB calabria = new ComboB("18", "Calabria");
		ComboB campania = new ComboB("15", "Campania");
		ComboB emiliaRomagna = new ComboB("8", "Emilia-Romagna");
		ComboB friuliVeneziaGiulia = new ComboB("6", "Friuli Venezia Giulia");
		ComboB lazio = new ComboB("12", "Lazio");
		ComboB liguria = new ComboB("7", "Liguria");
		ComboB lombardia = new ComboB("3", "Lombardia");
		ComboB marche = new ComboB("11", "Marche");
		ComboB molise = new ComboB("14", "Molise");
		ComboB pABolzano = new ComboB("21", "P.A. Bolzano");
		ComboB pATrento = new ComboB("22", "P.A. Trento");
		ComboB piemonte = new ComboB("1", "Piemonte");
		ComboB puglia = new ComboB("16", "Puglia");
		ComboB sardegna = new ComboB("20", "Sardegna");
		ComboB sicilia = new ComboB("19", "Sicilia");
		ComboB toscana = new ComboB("9", "Toscana");
		ComboB umbria = new ComboB("10", "Umbria");
		ComboB valleDAosta = new ComboB("2", "Valle d'Aosta");
		ComboB veneto = new ComboB("5", "Veneto");

		er.add(abruzzo);
		er.add(basilicata);
		er.add(calabria);
		er.add(campania);
		er.add(emiliaRomagna);
		er.add(friuliVeneziaGiulia);
		er.add(lazio);
		er.add(lombardia);
		er.add(marche);
		er.add(molise);
		er.add(liguria);
		er.add(pABolzano);
		er.add(pATrento);
		er.add(piemonte);
		er.add(puglia);
		er.add(sardegna);
		er.add(sicilia);
		er.add(toscana);
		er.add(umbria);
		er.add(valleDAosta);
		er.add(veneto);
		return er;
	}

	@Bean(name = "elencoProvince")
	public List<ComboB> elencoProvince() {
		List<ComboB> ep = new ArrayList<ComboB>();
		ComboB agrigento = new ComboB("84", "Agrigento");
		ep.add(agrigento);
		ComboB alessandria = new ComboB("6", "Alessandria");
		ep.add(alessandria);
		ComboB ancona = new ComboB("42", "Ancona");
		ep.add(ancona);
		ComboB aosta = new ComboB("7", "Aosta");
		ep.add(aosta);
		ComboB arezzo = new ComboB("51", "Arezzo");
		ep.add(arezzo);
		ComboB ascolipiceno = new ComboB("44", "Ascoli Piceno");
		ep.add(ascolipiceno);
		ComboB asti = new ComboB("5", "Asti");
		ep.add(asti);
		ComboB avellino = new ComboB("64", "Avellino");
		ep.add(avellino);
		ComboB bari = new ComboB("72", "Bari");
		ep.add(bari);
		ComboB barlettaandriatrani = new ComboB("110", "Barletta-Andria-Trani");
		ep.add(barlettaandriatrani);
		ComboB belluno = new ComboB("25", "Belluno");
		ep.add(belluno);
		ComboB benevento = new ComboB("62", "Benevento");
		ep.add(benevento);
		ComboB bergamo = new ComboB("16", "Bergamo");
		ep.add(bergamo);
		ComboB biella = new ComboB("96", "Biella");
		ep.add(biella);
		ComboB bologna = new ComboB("37", "Bologna");
		ep.add(bologna);
		ComboB bolzano = new ComboB("21", "Bolzano");
		ep.add(bolzano);
		ComboB brescia = new ComboB("17", "Brescia");
		ep.add(brescia);
		ComboB brindisi = new ComboB("74", "Brindisi");
		ep.add(brindisi);
		ComboB cagliari = new ComboB("92", "Cagliari");
		ep.add(cagliari);
		ComboB caltanissetta = new ComboB("85", "Caltanissetta");
		ep.add(caltanissetta);
		ComboB campobasso = new ComboB("70", "Campobasso");
		ep.add(campobasso);
		ComboB caserta = new ComboB("61", "Caserta");
		ep.add(caserta);
		ComboB catania = new ComboB("87", "Catania");
		ep.add(catania);
		ComboB catanzaro = new ComboB("79", "Catanzaro");
		ep.add(catanzaro);
		ComboB chieti = new ComboB("69", "Chieti");
		ep.add(chieti);
		ComboB como = new ComboB("13", "Como");
		ep.add(como);
		ComboB cosenza = new ComboB("78", "Cosenza");
		ep.add(cosenza);
		ComboB cremona = new ComboB("19", "Cremona");
		ep.add(cremona);
		ComboB crotone = new ComboB("101", "Crotone");
		ep.add(crotone);
		ComboB cuneo = new ComboB("4", "Cuneo");
		ep.add(cuneo);
		ComboB enna = new ComboB("86", "Enna");
		ep.add(enna);
		ComboB fermo = new ComboB("109", "Fermo");
		ep.add(fermo);
		ComboB ferrara = new ComboB("38", "Ferrara");
		ep.add(ferrara);
		ComboB firenze = new ComboB("48", "Firenze");
		ep.add(firenze);
		ComboB foggia = new ComboB("71", "Foggia");
		ep.add(foggia);
		ComboB forlicesena = new ComboB("40", "Forlì-Cesena");
		ep.add(forlicesena);
		ComboB frosinone = new ComboB("60", "Frosinone");
		ep.add(frosinone);
		ComboB genova = new ComboB("10", "Genova");
		ep.add(genova);
		ComboB gorizia = new ComboB("31", "Gorizia");
		ep.add(gorizia);
		ComboB grosseto = new ComboB("53", "Grosseto");
		ep.add(grosseto);
		ComboB imperia = new ComboB("8", "Imperia");
		ep.add(imperia);
		ComboB isernia = new ComboB("94", "Isernia");
		ep.add(isernia);
		ComboB laquila = new ComboB("66", "L'Aquila");
		ep.add(laquila);
		ComboB laspezia = new ComboB("11", "La Spezia");
		ep.add(laspezia);
		ComboB latina = new ComboB("59", "Latina");
		ep.add(latina);
		ComboB lecce = new ComboB("75", "Lecce");
		ep.add(lecce);
		ComboB lecco = new ComboB("97", "Lecco");
		ep.add(lecco);
		ComboB livorno = new ComboB("49", "Livorno");
		ep.add(livorno);
		ComboB lodi = new ComboB("98", "Lodi");
		ep.add(lodi);
		ComboB lucca = new ComboB("46", "Lucca");
		ep.add(lucca);
		ComboB macerata = new ComboB("43", "Macerata");
		ep.add(macerata);
		ComboB mantova = new ComboB("20", "Mantova");
		ep.add(mantova);
		ComboB massacarrara = new ComboB("45", "Massa Carrara");
		ep.add(massacarrara);
		ComboB matera = new ComboB("77", "Matera");
		ep.add(matera);
		ComboB messina = new ComboB("83", "Messina");
		ep.add(messina);
		ComboB milano = new ComboB("15", "Milano");
		ep.add(milano);
		ComboB modena = new ComboB("36", "Modena");
		ep.add(modena);
		ComboB monzaebrianza = new ComboB("108", "Monza e della Brianza");
		ep.add(monzaebrianza);
		ComboB napoli = new ComboB("63", "Napoli");
		ep.add(napoli);
		ComboB novara = new ComboB("3", "Novara");
		ep.add(novara);
		ComboB nuoro = new ComboB("91", "Nuoro");
		ep.add(nuoro);
		ComboB oristano = new ComboB("95", "Oristano");
		ep.add(oristano);
		ComboB padova = new ComboB("28", "Padova");
		ep.add(padova);
		ComboB palermo = new ComboB("82", "Palermo");
		ep.add(palermo);
		ComboB parma = new ComboB("34", "Parma");
		ep.add(parma);
		ComboB pavia = new ComboB("18", "Pavia");
		ep.add(pavia);
		ComboB perugia = new ComboB("54", "Perugia");
		ep.add(perugia);
		ComboB pesarourbino = new ComboB("41", "Pesaro e Urbino");
		ep.add(pesarourbino);
		ComboB pescara = new ComboB("68", "Pescara");
		ep.add(pescara);
		ComboB piacenza = new ComboB("33", "Piacenza");
		ep.add(piacenza);
		ComboB pisa = new ComboB("50", "Pisa");
		ep.add(pisa);
		ComboB pistoia = new ComboB("47", "Pistoia");
		ep.add(pistoia);
		ComboB pordenone = new ComboB("93", "Pordenone");
		ep.add(pordenone);
		ComboB potenza = new ComboB("76", "Potenza");
		ep.add(potenza);
		ComboB prato = new ComboB("100", "Prato");
		ep.add(prato);
		ComboB ragusa = new ComboB("88", "Ragusa");
		ep.add(ragusa);
		ComboB ravenna = new ComboB("39", "Ravenna");
		ep.add(ravenna);
		ComboB reggiocalabria = new ComboB("80", "Reggio di Calabria");
		ep.add(reggiocalabria);
		ComboB reggioemilia = new ComboB("35", "Reggio nell'Emilia");
		ep.add(reggioemilia);
		ComboB rieti = new ComboB("57", "Rieti");
		ep.add(rieti);
		ComboB rimini = new ComboB("99", "Rimini");
		ep.add(rimini);
		ComboB roma = new ComboB("58", "Roma");
		ep.add(roma);
		ComboB rovigo = new ComboB("29", "Rovigo");
		ep.add(rovigo);
		ComboB salerno = new ComboB("65", "Salerno");
		ep.add(salerno);
		ComboB sassari = new ComboB("90", "Sassari");
		ep.add(sassari);
		ComboB savona = new ComboB("9", "Savona");
		ep.add(savona);
		ComboB siena = new ComboB("52", "Siena");
		ep.add(siena);
		ComboB siracusa = new ComboB("89", "Siracusa");
		ep.add(siracusa);
		ComboB sondrio = new ComboB("14", "Sondrio");
		ep.add(sondrio);
		ComboB sudsardegna = new ComboB("111", "Sud Sardegna");
		ep.add(sudsardegna);
		ComboB taranto = new ComboB("73", "Taranto");
		ep.add(taranto);
		ComboB teramo = new ComboB("67", "Teramo");
		ep.add(teramo);
		ComboB terni = new ComboB("55", "Terni");
		ep.add(terni);
		ComboB torino = new ComboB("1", "Torino");
		ep.add(torino);
		ComboB trapani = new ComboB("81", "Trapani");
		ep.add(trapani);
		ComboB trento = new ComboB("22", "Trento");
		ep.add(trento);
		ComboB treviso = new ComboB("26", "Treviso");
		ep.add(treviso);
		ComboB trieste = new ComboB("32", "Trieste");
		ep.add(trieste);
		ComboB udine = new ComboB("30", "Udine");
		ep.add(udine);
		ComboB varese = new ComboB("12", "Varese");
		ep.add(varese);
		ComboB venezia = new ComboB("27", "Venezia");
		ep.add(venezia);
		ComboB verbanocusioossola = new ComboB("103", "Verbano-Cusio-Ossola");
		ep.add(verbanocusioossola);
		ComboB vercelli = new ComboB("2", "Vercelli");
		ep.add(vercelli);
		ComboB verona = new ComboB("23", "Verona");
		ep.add(verona);
		ComboB vibovalentia = new ComboB("102", "Vibo Valentia");
		ep.add(vibovalentia);
		ComboB vicenza = new ComboB("24", "Vicenza");
		ep.add(vicenza);
		ComboB viterbo = new ComboB("56", "Viterbo");
		ep.add(viterbo);
		return ep;
	}

}
