FROM openjdk:11
COPY target/covid19.be-0.0.1-SNAPSHOT.jar /home/giuseppe/Documents/java/workspace/git/covid19/docker/covid19be/
WORKDIR /home/giuseppe/Documents/java/workspace/git/covid19/docker/covid19be/
ENTRYPOINT ["java","-jar", "covid19.be-0.0.1-SNAPSHOT.jar"]